services:
  tg-signer:
    image: stars7/tg-signer:latest
    container_name: tg-signer
    ports:
      - "7001:7001"
    volumes:
      - ./tg-signer:/app/.signer
    environment:
      - TG_PROXY=socks5://192.168.1.100:7890 # 自行修改或删除
    restart: unless-stopped